// Comprehensive emoji database with searchable names
const emojis = [
    // Smileys & Emotion
    { symbol: '😀', names: ['grinning', 'smile', 'happy', 'smiley'] },
    { symbol: '😃', names: ['grinning big eyes', 'smile', 'happy'] },
    { symbol: '😄', names: ['grinning smiling eyes', 'smile', 'happy', 'joy'] },
    { symbol: '😁', names: ['beaming', 'grin', 'happy'] },
    { symbol: '😆', names: ['laughing', 'satisfied', 'lol', 'haha'] },
    { symbol: '😅', names: ['sweat smile', 'relief', 'phew'] },
    { symbol: '🤣', names: ['rofl', 'rolling laughing', 'lol', 'floor'] },
    { symbol: '😂', names: ['tears joy', 'crying laughing', 'lol'] },
    { symbol: '🙂', names: ['slightly smiling', 'smile'] },
    { symbol: '🙃', names: ['upside down', 'silly'] },
    { symbol: '😉', names: ['wink', 'flirt'] },
    { symbol: '😊', names: ['blush', 'happy', 'smile'] },
    { symbol: '😇', names: ['angel', 'halo', 'innocent'] },
    { symbol: '🥰', names: ['hearts', 'love', 'crush', 'adore'] },
    { symbol: '😍', names: ['heart eyes', 'love', 'crush'] },
    { symbol: '🤩', names: ['star struck', 'wow', 'amazed'] },
    { symbol: '😘', names: ['kiss', 'blow kiss', 'love'] },
    { symbol: '😗', names: ['kissing', 'kiss'] },
    { symbol: '😚', names: ['kissing closed eyes', 'kiss'] },
    { symbol: '😙', names: ['kissing smiling eyes', 'kiss'] },
    { symbol: '🥲', names: ['smiling tear', 'touched', 'grateful'] },
    { symbol: '😋', names: ['yum', 'delicious', 'savoring', 'tasty'] },
    { symbol: '😛', names: ['tongue', 'playful'] },
    { symbol: '😜', names: ['wink tongue', 'playful', 'silly'] },
    { symbol: '🤪', names: ['zany', 'crazy', 'wild'] },
    { symbol: '😝', names: ['squinting tongue', 'playful'] },
    { symbol: '🤑', names: ['money mouth', 'rich', 'dollar'] },
    { symbol: '🤗', names: ['hugging', 'hug', 'embrace'] },
    { symbol: '🤭', names: ['hand over mouth', 'oops', 'giggle'] },
    { symbol: '🤫', names: ['shushing', 'quiet', 'shh', 'silence'] },
    { symbol: '🤔', names: ['thinking', 'hmm', 'consider'] },
    { symbol: '🤐', names: ['zipper mouth', 'sealed lips', 'secret'] },
    { symbol: '🤨', names: ['raised eyebrow', 'skeptical', 'suspicious'] },
    { symbol: '😐', names: ['neutral', 'meh', 'straight face'] },
    { symbol: '😑', names: ['expressionless', 'blank'] },
    { symbol: '😶', names: ['no mouth', 'silent', 'speechless'] },
    { symbol: '😏', names: ['smirk', 'smug'] },
    { symbol: '😒', names: ['unamused', 'unhappy', 'annoyed'] },
    { symbol: '🙄', names: ['eye roll', 'whatever'] },
    { symbol: '😬', names: ['grimacing', 'awkward', 'eek'] },
    { symbol: '😮‍💨', names: ['exhale', 'sigh', 'relief'] },
    { symbol: '🤥', names: ['lying', 'pinocchio', 'liar'] },
    { symbol: '😌', names: ['relieved', 'content', 'peaceful'] },
    { symbol: '😔', names: ['pensive', 'sad', 'dejected'] },
    { symbol: '😪', names: ['sleepy', 'tired'] },
    { symbol: '🤤', names: ['drooling', 'drool'] },
    { symbol: '😴', names: ['sleeping', 'sleep', 'zzz'] },
    { symbol: '😷', names: ['mask', 'sick', 'medical'] },
    { symbol: '🤒', names: ['thermometer', 'sick', 'ill', 'fever'] },
    { symbol: '🤕', names: ['bandage', 'injured', 'hurt'] },
    { symbol: '🤢', names: ['nauseated', 'sick', 'gross'] },
    { symbol: '🤮', names: ['vomit', 'puke', 'sick'] },
    { symbol: '🤧', names: ['sneeze', 'achoo', 'sick'] },
    { symbol: '🥵', names: ['hot', 'heat', 'sweating'] },
    { symbol: '🥶', names: ['cold', 'freezing', 'frozen'] },
    { symbol: '🥴', names: ['woozy', 'dizzy', 'drunk'] },
    { symbol: '😵', names: ['dizzy', 'knocked out'] },
    { symbol: '🤯', names: ['exploding head', 'mind blown', 'shocked'] },
    { symbol: '🤠', names: ['cowboy', 'hat', 'western'] },
    { symbol: '🥳', names: ['party', 'celebration', 'birthday'] },
    { symbol: '🥸', names: ['disguise', 'incognito', 'glasses'] },
    { symbol: '😎', names: ['cool', 'sunglasses', 'awesome'] },
    { symbol: '🤓', names: ['nerd', 'geek', 'glasses'] },
    { symbol: '🧐', names: ['monocle', 'fancy', 'investigating'] },
    { symbol: '😕', names: ['confused', 'unsure'] },
    { symbol: '😟', names: ['worried', 'concerned'] },
    { symbol: '🙁', names: ['slightly frowning', 'sad'] },
    { symbol: '☹️', names: ['frowning', 'sad', 'unhappy'] },
    { symbol: '😮', names: ['wow', 'surprised', 'open mouth'] },
    { symbol: '😯', names: ['hushed', 'surprised'] },
    { symbol: '😲', names: ['astonished', 'shocked', 'amazed'] },
    { symbol: '😳', names: ['flushed', 'embarrassed', 'blushing'] },
    { symbol: '🥺', names: ['pleading', 'puppy eyes', 'begging'] },
    { symbol: '😦', names: ['frowning open mouth', 'surprised'] },
    { symbol: '😧', names: ['anguished', 'distressed'] },
    { symbol: '😨', names: ['fearful', 'scared', 'afraid'] },
    { symbol: '😰', names: ['anxious sweat', 'nervous'] },
    { symbol: '😥', names: ['sad relieved', 'disappointed'] },
    { symbol: '😢', names: ['crying', 'sad', 'tears'] },
    { symbol: '😭', names: ['loudly crying', 'sobbing', 'bawling'] },
    { symbol: '😱', names: ['screaming fear', 'shocked', 'omg'] },
    { symbol: '😖', names: ['confounded', 'frustrated'] },
    { symbol: '😣', names: ['persevering', 'struggling'] },
    { symbol: '😞', names: ['disappointed', 'sad'] },
    { symbol: '😓', names: ['downcast sweat', 'tired', 'stressed'] },
    { symbol: '😩', names: ['weary', 'tired', 'exhausted'] },
    { symbol: '😫', names: ['tired', 'exhausted', 'fed up'] },
    { symbol: '🥱', names: ['yawn', 'tired', 'bored'] },
    { symbol: '😤', names: ['triumph', 'proud', 'determined'] },
    { symbol: '😡', names: ['angry', 'mad', 'rage'] },
    { symbol: '😠', names: ['angry', 'mad', 'annoyed'] },
    { symbol: '🤬', names: ['cursing', 'swearing', 'symbols'] },
    { symbol: '😈', names: ['devil', 'evil', 'mischievous'] },
    { symbol: '👿', names: ['angry devil', 'evil'] },
    { symbol: '💀', names: ['skull', 'dead', 'death'] },
    { symbol: '☠️', names: ['skull crossbones', 'danger', 'poison'] },
    { symbol: '💩', names: ['poop', 'shit', 'crap'] },
    { symbol: '🤡', names: ['clown', 'joker'] },
    { symbol: '👹', names: ['ogre', 'monster', 'demon'] },
    { symbol: '👺', names: ['goblin', 'monster'] },
    { symbol: '👻', names: ['ghost', 'boo', 'spooky'] },
    { symbol: '👽', names: ['alien', 'ufo', 'extraterrestrial'] },
    { symbol: '👾', names: ['alien monster', 'space invader', 'video game'] },
    { symbol: '🤖', names: ['robot', 'bot'] },

    // Gestures & Body Parts
    { symbol: '👋', names: ['wave', 'hello', 'hi', 'bye'] },
    { symbol: '🤚', names: ['raised back hand', 'stop'] },
    { symbol: '🖐️', names: ['hand fingers splayed', 'five'] },
    { symbol: '✋', names: ['raised hand', 'stop', 'high five'] },
    { symbol: '🖖', names: ['vulcan salute', 'spock', 'star trek'] },
    { symbol: '👌', names: ['ok', 'okay', 'perfect'] },
    { symbol: '🤌', names: ['pinched fingers', 'italian'] },
    { symbol: '🤏', names: ['pinching', 'small', 'tiny'] },
    { symbol: '✌️', names: ['peace', 'victory', 'two'] },
    { symbol: '🤞', names: ['crossed fingers', 'luck', 'hope'] },
    { symbol: '🤟', names: ['love you', 'ily', 'rock'] },
    { symbol: '🤘', names: ['rock on', 'horns', 'metal'] },
    { symbol: '🤙', names: ['call me', 'shaka', 'hang loose'] },
    { symbol: '👈', names: ['backhand index pointing left', 'left', 'point'] },
    { symbol: '👉', names: ['backhand index pointing right', 'right', 'point'] },
    { symbol: '👆', names: ['backhand index pointing up', 'up', 'point'] },
    { symbol: '👇', names: ['backhand index pointing down', 'down', 'point'] },
    { symbol: '☝️', names: ['index pointing up', 'up', 'one'] },
    { symbol: '👍', names: ['thumbs up', 'like', 'yes', 'good', 'approve'] },
    { symbol: '👎', names: ['thumbs down', 'dislike', 'no', 'bad', 'disapprove'] },
    { symbol: '✊', names: ['fist', 'punch', 'power'] },
    { symbol: '👊', names: ['fist bump', 'punch'] },
    { symbol: '🤛', names: ['left fist bump', 'punch'] },
    { symbol: '🤜', names: ['right fist bump', 'punch'] },
    { symbol: '👏', names: ['clap', 'applause', 'clapping', 'congrats'] },
    { symbol: '🙌', names: ['raising hands', 'celebration', 'hooray', 'yay'] },
    { symbol: '👐', names: ['open hands', 'hug'] },
    { symbol: '🤲', names: ['palms up', 'prayer', 'dua'] },
    { symbol: '🤝', names: ['handshake', 'deal', 'agreement'] },
    { symbol: '🙏', names: ['folded hands', 'prayer', 'thank you', 'please', 'namaste'] },
    { symbol: '✍️', names: ['writing', 'write', 'pen'] },
    { symbol: '💅', names: ['nail polish', 'nails', 'manicure'] },
    { symbol: '🤳', names: ['selfie', 'camera', 'photo'] },
    { symbol: '💪', names: ['muscle', 'strong', 'flex', 'strength'] },
    { symbol: '🦾', names: ['mechanical arm', 'prosthetic'] },
    { symbol: '🦿', names: ['mechanical leg', 'prosthetic'] },
    { symbol: '🦵', names: ['leg'] },
    { symbol: '🦶', names: ['foot'] },
    { symbol: '👂', names: ['ear', 'listen'] },
    { symbol: '🦻', names: ['ear hearing aid'] },
    { symbol: '👃', names: ['nose', 'smell'] },
    { symbol: '🧠', names: ['brain', 'smart', 'intelligent'] },
    { symbol: '🫀', names: ['heart organ', 'anatomical heart'] },
    { symbol: '🫁', names: ['lungs'] },
    { symbol: '🦷', names: ['tooth', 'teeth', 'dental'] },
    { symbol: '🦴', names: ['bone'] },
    { symbol: '👀', names: ['eyes', 'looking', 'watching'] },
    { symbol: '👁️', names: ['eye'] },
    { symbol: '👅', names: ['tongue'] },
    { symbol: '👄', names: ['mouth', 'lips', 'kiss'] },

    // People & Body
    { symbol: '👶', names: ['baby', 'infant'] },
    { symbol: '🧒', names: ['child', 'kid'] },
    { symbol: '👦', names: ['boy', 'kid'] },
    { symbol: '👧', names: ['girl', 'kid'] },
    { symbol: '🧑', names: ['person', 'adult'] },
    { symbol: '👨', names: ['man', 'male'] },
    { symbol: '👩', names: ['woman', 'female'] },
    { symbol: '🧓', names: ['older person', 'elderly'] },
    { symbol: '👴', names: ['old man', 'elderly'] },
    { symbol: '👵', names: ['old woman', 'elderly'] },

    // Animals & Nature
    { symbol: '🐶', names: ['dog', 'puppy', 'pet'] },
    { symbol: '🐱', names: ['cat', 'kitty', 'pet'] },
    { symbol: '🐭', names: ['mouse', 'rat'] },
    { symbol: '🐹', names: ['hamster', 'pet'] },
    { symbol: '🐰', names: ['rabbit', 'bunny'] },
    { symbol: '🦊', names: ['fox'] },
    { symbol: '🐻', names: ['bear'] },
    { symbol: '🐼', names: ['panda', 'bear'] },
    { symbol: '🐨', names: ['koala'] },
    { symbol: '🐯', names: ['tiger'] },
    { symbol: '🦁', names: ['lion'] },
    { symbol: '🐮', names: ['cow'] },
    { symbol: '🐷', names: ['pig'] },
    { symbol: '🐸', names: ['frog'] },
    { symbol: '🐵', names: ['monkey'] },
    { symbol: '🙈', names: ['see no evil', 'monkey'] },
    { symbol: '🙉', names: ['hear no evil', 'monkey'] },
    { symbol: '🙊', names: ['speak no evil', 'monkey'] },
    { symbol: '🐒', names: ['monkey'] },
    { symbol: '🐔', names: ['chicken', 'rooster'] },
    { symbol: '🐧', names: ['penguin'] },
    { symbol: '🐦', names: ['bird'] },
    { symbol: '🐤', names: ['baby chick', 'bird'] },
    { symbol: '🐣', names: ['hatching chick', 'egg'] },
    { symbol: '🐥', names: ['chick', 'baby bird'] },
    { symbol: '🦆', names: ['duck'] },
    { symbol: '🦅', names: ['eagle'] },
    { symbol: '🦉', names: ['owl'] },
    { symbol: '🦇', names: ['bat'] },
    { symbol: '🐺', names: ['wolf'] },
    { symbol: '🐗', names: ['boar', 'pig'] },
    { symbol: '🐴', names: ['horse'] },
    { symbol: '🦄', names: ['unicorn', 'magical'] },
    { symbol: '🐝', names: ['bee', 'honey'] },
    { symbol: '🪱', names: ['worm'] },
    { symbol: '🐛', names: ['bug', 'caterpillar'] },
    { symbol: '🦋', names: ['butterfly'] },
    { symbol: '🐌', names: ['snail', 'slow'] },
    { symbol: '🐞', names: ['ladybug', 'bug'] },
    { symbol: '🐜', names: ['ant', 'bug'] },
    { symbol: '🪰', names: ['fly'] },
    { symbol: '🪲', names: ['beetle', 'bug'] },
    { symbol: '🦗', names: ['cricket'] },
    { symbol: '🕷️', names: ['spider'] },
    { symbol: '🦂', names: ['scorpion'] },
    { symbol: '🦟', names: ['mosquito'] },
    { symbol: '🦠', names: ['microbe', 'virus', 'bacteria', 'germ'] },
    { symbol: '🐢', names: ['turtle', 'slow'] },
    { symbol: '🐍', names: ['snake'] },
    { symbol: '🦎', names: ['lizard'] },
    { symbol: '🦖', names: ['t-rex', 'dinosaur'] },
    { symbol: '🦕', names: ['dinosaur', 'brontosaurus'] },
    { symbol: '🐙', names: ['octopus'] },
    { symbol: '🦑', names: ['squid'] },
    { symbol: '🦐', names: ['shrimp'] },
    { symbol: '🦞', names: ['lobster'] },
    { symbol: '🦀', names: ['crab'] },
    { symbol: '🐡', names: ['blowfish', 'pufferfish'] },
    { symbol: '🐠', names: ['tropical fish'] },
    { symbol: '🐟', names: ['fish'] },
    { symbol: '🐬', names: ['dolphin'] },
    { symbol: '🐳', names: ['whale', 'spouting'] },
    { symbol: '🐋', names: ['whale'] },
    { symbol: '🦈', names: ['shark'] },
    { symbol: '🐊', names: ['crocodile', 'alligator'] },
    { symbol: '🐅', names: ['tiger'] },
    { symbol: '🐆', names: ['leopard'] },
    { symbol: '🦓', names: ['zebra'] },
    { symbol: '🦍', names: ['gorilla'] },
    { symbol: '🦧', names: ['orangutan'] },
    { symbol: '🦣', names: ['mammoth', 'elephant'] },
    { symbol: '🐘', names: ['elephant'] },
    { symbol: '🦛', names: ['hippo', 'hippopotamus'] },
    { symbol: '🦏', names: ['rhino', 'rhinoceros'] },
    { symbol: '🐪', names: ['camel', 'dromedary'] },
    { symbol: '🐫', names: ['two hump camel', 'bactrian'] },
    { symbol: '🦒', names: ['giraffe'] },
    { symbol: '🦘', names: ['kangaroo'] },
    { symbol: '🦬', names: ['bison'] },
    { symbol: '🐃', names: ['water buffalo'] },
    { symbol: '🐂', names: ['ox', 'bull'] },
    { symbol: '🐄', names: ['cow'] },
    { symbol: '🐎', names: ['horse', 'racing'] },
    { symbol: '🐖', names: ['pig'] },
    { symbol: '🐏', names: ['ram', 'sheep'] },
    { symbol: '🐑', names: ['sheep', 'ewe'] },
    { symbol: '🦙', names: ['llama'] },
    { symbol: '🐐', names: ['goat'] },
    { symbol: '🦌', names: ['deer'] },
    { symbol: '🐕', names: ['dog', 'pet'] },
    { symbol: '🐩', names: ['poodle', 'dog'] },
    { symbol: '🦮', names: ['guide dog', 'service dog'] },
    { symbol: '🐕‍🦺', names: ['service dog'] },
    { symbol: '🐈', names: ['cat', 'pet'] },
    { symbol: '🐈‍⬛', names: ['black cat'] },
    { symbol: '🪶', names: ['feather'] },
    { symbol: '🐓', names: ['rooster', 'chicken'] },
    { symbol: '🦃', names: ['turkey'] },
    { symbol: '🦤', names: ['dodo'] },
    { symbol: '🦚', names: ['peacock'] },
    { symbol: '🦜', names: ['parrot'] },
    { symbol: '🦢', names: ['swan'] },
    { symbol: '🦩', names: ['flamingo'] },
    { symbol: '🕊️', names: ['dove', 'peace'] },
    { symbol: '🐇', names: ['rabbit'] },
    { symbol: '🦝', names: ['raccoon'] },
    { symbol: '🦨', names: ['skunk'] },
    { symbol: '🦡', names: ['badger'] },
    { symbol: '🦫', names: ['beaver'] },
    { symbol: '🦦', names: ['otter'] },
    { symbol: '🦥', names: ['sloth', 'slow'] },
    { symbol: '🐁', names: ['mouse'] },
    { symbol: '🐀', names: ['rat'] },
    { symbol: '🐿️', names: ['chipmunk', 'squirrel'] },
    { symbol: '🦔', names: ['hedgehog'] },

    // Food & Drink
    { symbol: '🍇', names: ['grapes', 'fruit'] },
    { symbol: '🍈', names: ['melon', 'fruit'] },
    { symbol: '🍉', names: ['watermelon', 'fruit'] },
    { symbol: '🍊', names: ['orange', 'fruit', 'tangerine'] },
    { symbol: '🍋', names: ['lemon', 'fruit'] },
    { symbol: '🍌', names: ['banana', 'fruit'] },
    { symbol: '🍍', names: ['pineapple', 'fruit'] },
    { symbol: '🥭', names: ['mango', 'fruit'] },
    { symbol: '🍎', names: ['apple', 'red apple', 'fruit'] },
    { symbol: '🍏', names: ['green apple', 'fruit'] },
    { symbol: '🍐', names: ['pear', 'fruit'] },
    { symbol: '🍑', names: ['peach', 'fruit'] },
    { symbol: '🍒', names: ['cherries', 'fruit'] },
    { symbol: '🍓', names: ['strawberry', 'fruit'] },
    { symbol: '🫐', names: ['blueberries', 'fruit'] },
    { symbol: '🥝', names: ['kiwi', 'fruit'] },
    { symbol: '🍅', names: ['tomato', 'vegetable'] },
    { symbol: '🫒', names: ['olive'] },
    { symbol: '🥥', names: ['coconut'] },
    { symbol: '🥑', names: ['avocado'] },
    { symbol: '🍆', names: ['eggplant', 'aubergine', 'vegetable'] },
    { symbol: '🥔', names: ['potato', 'vegetable'] },
    { symbol: '🥕', names: ['carrot', 'vegetable'] },
    { symbol: '🌽', names: ['corn', 'vegetable'] },
    { symbol: '🌶️', names: ['hot pepper', 'chili', 'spicy'] },
    { symbol: '🫑', names: ['bell pepper', 'vegetable'] },
    { symbol: '🥒', names: ['cucumber', 'pickle', 'vegetable'] },
    { symbol: '🥬', names: ['leafy green', 'lettuce', 'vegetable'] },
    { symbol: '🥦', names: ['broccoli', 'vegetable'] },
    { symbol: '🧄', names: ['garlic'] },
    { symbol: '🧅', names: ['onion'] },
    { symbol: '🍄', names: ['mushroom'] },
    { symbol: '🥜', names: ['peanuts', 'nuts'] },
    { symbol: '🌰', names: ['chestnut', 'nut'] },
    { symbol: '🍞', names: ['bread', 'loaf'] },
    { symbol: '🥐', names: ['croissant', 'pastry'] },
    { symbol: '🥖', names: ['baguette', 'bread', 'french'] },
    { symbol: '🫓', names: ['flatbread', 'pita'] },
    { symbol: '🥨', names: ['pretzel'] },
    { symbol: '🥯', names: ['bagel'] },
    { symbol: '🥞', names: ['pancakes', 'breakfast'] },
    { symbol: '🧇', names: ['waffle', 'breakfast'] },
    { symbol: '🧀', names: ['cheese'] },
    { symbol: '🍖', names: ['meat', 'bone'] },
    { symbol: '🍗', names: ['chicken', 'poultry', 'drumstick'] },
    { symbol: '🥩', names: ['steak', 'meat'] },
    { symbol: '🥓', names: ['bacon'] },
    { symbol: '🍔', names: ['burger', 'hamburger'] },
    { symbol: '🍟', names: ['fries', 'french fries'] },
    { symbol: '🍕', names: ['pizza'] },
    { symbol: '🌭', names: ['hot dog', 'hotdog'] },
    { symbol: '🥪', names: ['sandwich'] },
    { symbol: '🌮', names: ['taco', 'mexican'] },
    { symbol: '🌯', names: ['burrito', 'wrap', 'mexican'] },
    { symbol: '🫔', names: ['tamale', 'mexican'] },
    { symbol: '🥙', names: ['stuffed flatbread', 'gyro', 'kebab'] },
    { symbol: '🧆', names: ['falafel'] },
    { symbol: '🥚', names: ['egg'] },
    { symbol: '🍳', names: ['cooking', 'fried egg', 'breakfast'] },
    { symbol: '🥘', names: ['paella', 'shallow pan food'] },
    { symbol: '🍲', names: ['pot food', 'stew', 'soup'] },
    { symbol: '🫕', names: ['fondue'] },
    { symbol: '🥣', names: ['bowl spoon', 'cereal'] },
    { symbol: '🥗', names: ['salad', 'green salad'] },
    { symbol: '🍿', names: ['popcorn', 'movie'] },
    { symbol: '🧈', names: ['butter'] },
    { symbol: '🧂', names: ['salt'] },
    { symbol: '🥫', names: ['canned food', 'can'] },
    { symbol: '🍱', names: ['bento', 'box', 'japanese'] },
    { symbol: '🍘', names: ['rice cracker', 'japanese'] },
    { symbol: '🍙', names: ['rice ball', 'onigiri', 'japanese'] },
    { symbol: '🍚', names: ['rice', 'cooked rice'] },
    { symbol: '🍛', names: ['curry', 'rice'] },
    { symbol: '🍜', names: ['ramen', 'noodles', 'steaming bowl'] },
    { symbol: '🍝', names: ['spaghetti', 'pasta'] },
    { symbol: '🍠', names: ['sweet potato', 'roasted'] },
    { symbol: '🍢', names: ['oden', 'japanese', 'skewer'] },
    { symbol: '🍣', names: ['sushi', 'japanese'] },
    { symbol: '🍤', names: ['fried shrimp', 'tempura'] },
    { symbol: '🍥', names: ['fish cake', 'naruto', 'japanese'] },
    { symbol: '🥮', names: ['moon cake', 'chinese'] },
    { symbol: '🍡', names: ['dango', 'japanese', 'dessert'] },
    { symbol: '🥟', names: ['dumpling', 'gyoza'] },
    { symbol: '🥠', names: ['fortune cookie', 'cookie'] },
    { symbol: '🥡', names: ['takeout box', 'chinese'] },
    { symbol: '🦀', names: ['crab', 'seafood'] },
    { symbol: '🦞', names: ['lobster', 'seafood'] },
    { symbol: '🦐', names: ['shrimp', 'seafood'] },
    { symbol: '🦑', names: ['squid', 'seafood'] },
    { symbol: '🦪', names: ['oyster', 'seafood'] },
    { symbol: '🍦', names: ['ice cream', 'soft serve', 'dessert'] },
    { symbol: '🍧', names: ['shaved ice', 'dessert'] },
    { symbol: '🍨', names: ['ice cream', 'dessert'] },
    { symbol: '🍩', names: ['donut', 'doughnut', 'dessert'] },
    { symbol: '🍪', names: ['cookie', 'dessert'] },
    { symbol: '🎂', names: ['birthday cake', 'cake', 'dessert'] },
    { symbol: '🍰', names: ['cake', 'shortcake', 'dessert'] },
    { symbol: '🧁', names: ['cupcake', 'dessert'] },
    { symbol: '🥧', names: ['pie', 'dessert'] },
    { symbol: '🍫', names: ['chocolate', 'bar', 'dessert'] },
    { symbol: '🍬', names: ['candy', 'sweet'] },
    { symbol: '🍭', names: ['lollipop', 'candy'] },
    { symbol: '🍮', names: ['custard', 'flan', 'pudding', 'dessert'] },
    { symbol: '🍯', names: ['honey', 'pot'] },
    { symbol: '🍼', names: ['baby bottle', 'milk'] },
    { symbol: '🥛', names: ['milk', 'glass'] },
    { symbol: '☕', names: ['coffee', 'hot beverage'] },
    { symbol: '🫖', names: ['teapot', 'tea'] },
    { symbol: '🍵', names: ['tea', 'green tea', 'hot'] },
    { symbol: '🍶', names: ['sake', 'japanese'] },
    { symbol: '🍾', names: ['champagne', 'bottle', 'celebration'] },
    { symbol: '🍷', names: ['wine', 'glass', 'red wine'] },
    { symbol: '🍸', names: ['cocktail', 'martini', 'drink'] },
    { symbol: '🍹', names: ['tropical drink', 'cocktail'] },
    { symbol: '🍺', names: ['beer', 'mug'] },
    { symbol: '🍻', names: ['beers', 'cheers', 'clinking'] },
    { symbol: '🥂', names: ['champagne', 'clinking glasses', 'cheers', 'toast'] },
    { symbol: '🥃', names: ['whiskey', 'tumbler', 'glass'] },
    { symbol: '🥤', names: ['cup straw', 'soda', 'soft drink'] },
    { symbol: '🧋', names: ['bubble tea', 'boba'] },
    { symbol: '🧃', names: ['juice box', 'beverage'] },
    { symbol: '🧉', names: ['mate', 'drink'] },
    { symbol: '🧊', names: ['ice', 'cube'] },

    // Activities & Sports
    { symbol: '⚽', names: ['soccer', 'football', 'ball'] },
    { symbol: '🏀', names: ['basketball', 'ball'] },
    { symbol: '🏈', names: ['american football', 'ball'] },
    { symbol: '⚾', names: ['baseball', 'ball'] },
    { symbol: '🥎', names: ['softball', 'ball'] },
    { symbol: '🎾', names: ['tennis', 'ball'] },
    { symbol: '🏐', names: ['volleyball', 'ball'] },
    { symbol: '🏉', names: ['rugby', 'ball'] },
    { symbol: '🥏', names: ['frisbee', 'flying disc'] },
    { symbol: '🎱', names: ['pool', '8 ball', 'billiards'] },
    { symbol: '🪀', names: ['yo-yo', 'yoyo'] },
    { symbol: '🏓', names: ['ping pong', 'table tennis'] },
    { symbol: '🏸', names: ['badminton'] },
    { symbol: '🏒', names: ['hockey', 'ice hockey'] },
    { symbol: '🏑', names: ['field hockey'] },
    { symbol: '🥍', names: ['lacrosse'] },
    { symbol: '🏏', names: ['cricket'] },
    { symbol: '🪃', names: ['boomerang'] },
    { symbol: '🥅', names: ['goal', 'net'] },
    { symbol: '⛳', names: ['golf', 'flag hole'] },
    { symbol: '🪁', names: ['kite'] },
    { symbol: '🏹', names: ['bow arrow', 'archery'] },
    { symbol: '🎣', names: ['fishing', 'pole'] },
    { symbol: '🤿', names: ['diving', 'mask'] },
    { symbol: '🥊', names: ['boxing', 'glove'] },
    { symbol: '🥋', names: ['martial arts', 'karate', 'judo'] },
    { symbol: '🎽', names: ['running', 'shirt', 'athletics'] },
    { symbol: '🛹', names: ['skateboard', 'skating'] },
    { symbol: '🛼', names: ['roller skate'] },
    { symbol: '🛷', names: ['sled', 'sledding'] },
    { symbol: '⛸️', names: ['ice skate', 'skating'] },
    { symbol: '🥌', names: ['curling', 'stone'] },
    { symbol: '🎿', names: ['ski', 'skiing'] },
    { symbol: '⛷️', names: ['skier', 'skiing'] },
    { symbol: '🏂', names: ['snowboard', 'snowboarding'] },
    { symbol: '🪂', names: ['parachute', 'skydiving'] },
    { symbol: '🏋️', names: ['weight lifting', 'gym', 'lifting'] },
    { symbol: '🤼', names: ['wrestling', 'wrestlers'] },
    { symbol: '🤸', names: ['cartwheel', 'gymnastics'] },
    { symbol: '🤺', names: ['fencing', 'fencer'] },
    { symbol: '🤾', names: ['handball'] },
    { symbol: '🏌️', names: ['golf', 'golfer'] },
    { symbol: '🏇', names: ['horse racing', 'jockey'] },
    { symbol: '🧘', names: ['yoga', 'meditation', 'lotus'] },
    { symbol: '🏄', names: ['surfing', 'surfer'] },
    { symbol: '🏊', names: ['swimming', 'swimmer'] },
    { symbol: '🤽', names: ['water polo'] },
    { symbol: '🚣', names: ['rowing', 'boat'] },
    { symbol: '🧗', names: ['climbing', 'climber'] },
    { symbol: '🚴', names: ['cycling', 'biking', 'bicycle'] },
    { symbol: '🚵', names: ['mountain biking', 'bike'] },
    { symbol: '🤹', names: ['juggling', 'juggler'] },

    // Travel & Places
    { symbol: '🚗', names: ['car', 'automobile', 'red car'] },
    { symbol: '🚕', names: ['taxi', 'cab'] },
    { symbol: '🚙', names: ['suv', 'sport utility vehicle'] },
    { symbol: '🚌', names: ['bus'] },
    { symbol: '🚎', names: ['trolleybus'] },
    { symbol: '🏎️', names: ['racing car', 'race car'] },
    { symbol: '🚓', names: ['police car', 'cop'] },
    { symbol: '🚑', names: ['ambulance', 'emergency'] },
    { symbol: '🚒', names: ['fire engine', 'fire truck'] },
    { symbol: '🚐', names: ['minibus', 'van'] },
    { symbol: '🛻', names: ['pickup truck'] },
    { symbol: '🚚', names: ['delivery truck', 'truck'] },
    { symbol: '🚛', names: ['articulated lorry', 'semi truck'] },
    { symbol: '🚜', names: ['tractor', 'farm'] },
    { symbol: '🦯', names: ['probing cane', 'white cane'] },
    { symbol: '🦽', names: ['manual wheelchair'] },
    { symbol: '🦼', names: ['motorized wheelchair'] },
    { symbol: '🛴', names: ['scooter', 'kick scooter'] },
    { symbol: '🚲', names: ['bicycle', 'bike'] },
    { symbol: '🛵', names: ['motor scooter', 'moped', 'vespa'] },
    { symbol: '🏍️', names: ['motorcycle', 'motorbike'] },
    { symbol: '🛺', names: ['auto rickshaw', 'tuk tuk'] },
    { symbol: '🚨', names: ['police light', 'siren', 'emergency'] },
    { symbol: '🚔', names: ['oncoming police car'] },
    { symbol: '🚍', names: ['oncoming bus'] },
    { symbol: '🚘', names: ['oncoming car'] },
    { symbol: '🚖', names: ['oncoming taxi'] },
    { symbol: '🚡', names: ['aerial tramway', 'cable car'] },
    { symbol: '🚠', names: ['mountain cableway', 'gondola'] },
    { symbol: '🚟', names: ['suspension railway'] },
    { symbol: '🚃', names: ['railway car', 'tram'] },
    { symbol: '🚋', names: ['tram car'] },
    { symbol: '🚞', names: ['mountain railway'] },
    { symbol: '🚝', names: ['monorail'] },
    { symbol: '🚄', names: ['high speed train', 'bullet train'] },
    { symbol: '🚅', names: ['bullet train', 'shinkansen'] },
    { symbol: '🚈', names: ['light rail', 'train'] },
    { symbol: '🚂', names: ['locomotive', 'steam train'] },
    { symbol: '🚆', names: ['train'] },
    { symbol: '🚇', names: ['metro', 'subway'] },
    { symbol: '🚊', names: ['tram', 'trolley'] },
    { symbol: '🚉', names: ['station', 'train station'] },
    { symbol: '✈️', names: ['airplane', 'plane', 'flight'] },
    { symbol: '🛫', names: ['airplane departure', 'takeoff'] },
    { symbol: '🛬', names: ['airplane arrival', 'landing'] },
    { symbol: '🛩️', names: ['small airplane'] },
    { symbol: '💺', names: ['seat', 'airplane seat'] },
    { symbol: '🛰️', names: ['satellite'] },
    { symbol: '🚁', names: ['helicopter'] },
    { symbol: '🛶', names: ['canoe', 'kayak'] },
    { symbol: '⛵', names: ['sailboat', 'boat'] },
    { symbol: '🚤', names: ['speedboat', 'boat'] },
    { symbol: '🛥️', names: ['motor boat'] },
    { symbol: '🛳️', names: ['passenger ship', 'cruise'] },
    { symbol: '⛴️', names: ['ferry'] },
    { symbol: '🚢', names: ['ship'] },
    { symbol: '⚓', names: ['anchor'] },
    { symbol: '⛽', names: ['fuel', 'gas pump', 'gas station'] },
    { symbol: '🚧', names: ['construction', 'barrier'] },
    { symbol: '🚦', names: ['traffic light', 'vertical'] },
    { symbol: '🚥', names: ['traffic light', 'horizontal'] },
    { symbol: '🗺️', names: ['world map', 'map'] },
    { symbol: '🗿', names: ['moai', 'easter island', 'statue'] },
    { symbol: '🗽', names: ['statue of liberty', 'liberty'] },
    { symbol: '🗼', names: ['tokyo tower', 'tower'] },
    { symbol: '⛩️', names: ['shrine', 'torii', 'japanese'] },
    { symbol: '🕌', names: ['mosque', 'islam'] },
    { symbol: '🛕', names: ['hindu temple'] },
    { symbol: '🕍', names: ['synagogue', 'jewish'] },
    { symbol: '⛪', names: ['church', 'christian'] },
    { symbol: '🕋', names: ['kaaba', 'mecca', 'islam'] },
    { symbol: '⛲', names: ['fountain'] },
    { symbol: '⛺', names: ['tent', 'camping'] },
    { symbol: '🏕️', names: ['camping'] },
    { symbol: '🏖️', names: ['beach', 'umbrella'] },
    { symbol: '🏜️', names: ['desert'] },
    { symbol: '🏝️', names: ['island', 'desert island'] },
    { symbol: '🏞️', names: ['national park', 'park'] },
    { symbol: '🏟️', names: ['stadium'] },
    { symbol: '🏛️', names: ['classical building', 'museum'] },
    { symbol: '🏗️', names: ['construction', 'building'] },
    { symbol: '🧱', names: ['brick', 'bricks'] },
    { symbol: '🏘️', names: ['houses'] },
    { symbol: '🏚️', names: ['derelict house', 'abandoned'] },
    { symbol: '🏠', names: ['house', 'home'] },
    { symbol: '🏡', names: ['house garden', 'home'] },
    { symbol: '🏢', names: ['office', 'building'] },
    { symbol: '🏣', names: ['post office', 'japanese'] },
    { symbol: '🏤', names: ['post office', 'european'] },
    { symbol: '🏥', names: ['hospital'] },
    { symbol: '🏦', names: ['bank'] },
    { symbol: '🏨', names: ['hotel'] },
    { symbol: '🏩', names: ['love hotel'] },
    { symbol: '🏪', names: ['convenience store', 'store'] },
    { symbol: '🏫', names: ['school'] },
    { symbol: '🏬', names: ['department store', 'mall'] },
    { symbol: '🏭', names: ['factory'] },
    { symbol: '🏯', names: ['castle', 'japanese'] },
    { symbol: '🏰', names: ['castle', 'european'] },
    { symbol: '💒', names: ['wedding', 'church'] },
    { symbol: '🗼', names: ['tower'] },

    // Objects
    { symbol: '⌚', names: ['watch', 'time'] },
    { symbol: '📱', names: ['phone', 'mobile', 'iphone', 'smartphone'] },
    { symbol: '📲', names: ['phone arrow', 'call'] },
    { symbol: '💻', names: ['laptop', 'computer'] },
    { symbol: '⌨️', names: ['keyboard'] },
    { symbol: '🖥️', names: ['desktop', 'computer'] },
    { symbol: '🖨️', names: ['printer'] },
    { symbol: '🖱️', names: ['mouse', 'computer mouse'] },
    { symbol: '🖲️', names: ['trackball'] },
    { symbol: '🕹️', names: ['joystick', 'gaming'] },
    { symbol: '🗜️', names: ['clamp', 'compression'] },
    { symbol: '💾', names: ['floppy disk', 'save'] },
    { symbol: '💿', names: ['cd', 'disc'] },
    { symbol: '📀', names: ['dvd', 'disc'] },
    { symbol: '📼', names: ['vhs', 'videocassette'] },
    { symbol: '📷', names: ['camera'] },
    { symbol: '📸', names: ['camera flash', 'photo'] },
    { symbol: '📹', names: ['video camera'] },
    { symbol: '🎥', names: ['movie camera', 'film'] },
    { symbol: '📽️', names: ['film projector', 'cinema'] },
    { symbol: '🎞️', names: ['film frames'] },
    { symbol: '📞', names: ['telephone', 'phone'] },
    { symbol: '☎️', names: ['telephone', 'landline'] },
    { symbol: '📟', names: ['pager', 'beeper'] },
    { symbol: '📠', names: ['fax'] },
    { symbol: '📺', names: ['television', 'tv'] },
    { symbol: '📻', names: ['radio'] },
    { symbol: '🎙️', names: ['microphone', 'studio'] },
    { symbol: '🎚️', names: ['level slider'] },
    { symbol: '🎛️', names: ['control knobs'] },
    { symbol: '🧭', names: ['compass'] },
    { symbol: '⏱️', names: ['stopwatch', 'timer'] },
    { symbol: '⏲️', names: ['timer clock'] },
    { symbol: '⏰', names: ['alarm clock', 'clock'] },
    { symbol: '🕰️', names: ['mantelpiece clock'] },
    { symbol: '⌛', names: ['hourglass'] },
    { symbol: '⏳', names: ['hourglass flowing', 'time'] },
    { symbol: '📡', names: ['satellite antenna', 'antenna'] },
    { symbol: '🔋', names: ['battery'] },
    { symbol: '🔌', names: ['plug', 'electric'] },
    { symbol: '💡', names: ['bulb', 'light', 'idea'] },
    { symbol: '🔦', names: ['flashlight', 'torch'] },
    { symbol: '🕯️', names: ['candle'] },
    { symbol: '🪔', names: ['diya lamp', 'oil lamp'] },
    { symbol: '🧯', names: ['fire extinguisher'] },
    { symbol: '🛢️', names: ['oil drum', 'barrel'] },
    { symbol: '💸', names: ['money wings', 'flying money'] },
    { symbol: '💵', names: ['dollar', 'money', 'bill'] },
    { symbol: '💴', names: ['yen', 'money'] },
    { symbol: '💶', names: ['euro', 'money'] },
    { symbol: '💷', names: ['pound', 'money'] },
    { symbol: '🪙', names: ['coin', 'money'] },
    { symbol: '💰', names: ['money bag', 'rich'] },
    { symbol: '💳', names: ['credit card', 'card', 'payment'] },
    { symbol: '🧾', names: ['receipt'] },
    { symbol: '💎', names: ['gem', 'diamond', 'jewel'] },
    { symbol: '⚖️', names: ['balance scale', 'justice', 'law'] },
    { symbol: '🧰', names: ['toolbox'] },
    { symbol: '🔧', names: ['wrench', 'tool', 'spanner'] },
    { symbol: '🔨', names: ['hammer', 'tool'] },
    { symbol: '⚒️', names: ['hammer pick', 'tools'] },
    { symbol: '🛠️', names: ['hammer wrench', 'tools'] },
    { symbol: '⛏️', names: ['pick', 'mining'] },
    { symbol: '🪚', names: ['saw', 'carpentry'] },
    { symbol: '🔩', names: ['nut bolt', 'bolt'] },
    { symbol: '⚙️', names: ['gear', 'settings'] },
    { symbol: '🧱', names: ['brick'] },
    { symbol: '⛓️', names: ['chains', 'link'] },
    { symbol: '🧲', names: ['magnet'] },
    { symbol: '🔫', names: ['gun', 'pistol', 'water gun'] },
    { symbol: '💣', names: ['bomb'] },
    { symbol: '🧨', names: ['firecracker', 'dynamite'] },
    { symbol: '🪓', names: ['axe'] },
    { symbol: '🔪', names: ['knife', 'blade'] },
    { symbol: '🗡️', names: ['dagger', 'knife'] },
    { symbol: '⚔️', names: ['crossed swords', 'battle'] },
    { symbol: '🛡️', names: ['shield', 'protection'] },
    { symbol: '🚬', names: ['cigarette', 'smoking'] },
    { symbol: '⚰️', names: ['coffin'] },
    { symbol: '🪦', names: ['headstone', 'grave'] },
    { symbol: '⚱️', names: ['urn', 'funeral'] },
    { symbol: '🏺', names: ['amphora', 'jar'] },
    { symbol: '🔮', names: ['crystal ball', 'fortune'] },
    { symbol: '📿', names: ['prayer beads', 'beads'] },
    { symbol: '🧿', names: ['nazar', 'evil eye'] },
    { symbol: '💈', names: ['barber pole'] },
    { symbol: '⚗️', names: ['alembic', 'chemistry'] },
    { symbol: '🔭', names: ['telescope', 'astronomy'] },
    { symbol: '🔬', names: ['microscope', 'science'] },
    { symbol: '🕳️', names: ['hole'] },
    { symbol: '🩹', names: ['bandage', 'adhesive'] },
    { symbol: '🩺', names: ['stethoscope', 'doctor'] },
    { symbol: '💊', names: ['pill', 'medicine', 'drug'] },
    { symbol: '💉', names: ['syringe', 'needle', 'injection'] },
    { symbol: '🩸', names: ['blood', 'drop'] },
    { symbol: '🧬', names: ['dna', 'genetics'] },
    { symbol: '🦠', names: ['microbe', 'virus', 'bacteria'] },
    { symbol: '🧫', names: ['petri dish', 'bacteria'] },
    { symbol: '🧪', names: ['test tube', 'chemistry'] },
    { symbol: '🌡️', names: ['thermometer', 'temperature'] },
    { symbol: '🧹', names: ['broom', 'cleaning', 'sweep'] },
    { symbol: '🧺', names: ['basket'] },
    { symbol: '🧻', names: ['toilet paper', 'roll'] },
    { symbol: '🚽', names: ['toilet', 'bathroom'] },
    { symbol: '🚰', names: ['water', 'potable water'] },
    { symbol: '🚿', names: ['shower', 'bath'] },
    { symbol: '🛁', names: ['bathtub', 'bath'] },
    { symbol: '🪒', names: ['razor', 'shave'] },
    { symbol: '🧴', names: ['lotion', 'bottle'] },
    { symbol: '🧷', names: ['safety pin'] },
    { symbol: '🧹', names: ['broom'] },
    { symbol: '🧽', names: ['sponge', 'cleaning'] },
    { symbol: '🧼', names: ['soap', 'bar'] },
    { symbol: '🪥', names: ['toothbrush'] },
    { symbol: '🪒', names: ['razor'] },
    { symbol: '🧴', names: ['lotion bottle'] },
    { symbol: '🧵', names: ['thread', 'sewing'] },
    { symbol: '🧶', names: ['yarn', 'knitting'] },
    { symbol: '🪡', names: ['sewing needle', 'needle'] },
    { symbol: '🪢', names: ['knot'] },
    { symbol: '🧳', names: ['luggage', 'suitcase', 'travel'] },

    // Symbols
    { symbol: '❤️', names: ['heart', 'love', 'red heart'] },
    { symbol: '🧡', names: ['orange heart', 'love'] },
    { symbol: '💛', names: ['yellow heart', 'love'] },
    { symbol: '💚', names: ['green heart', 'love'] },
    { symbol: '💙', names: ['blue heart', 'love'] },
    { symbol: '💜', names: ['purple heart', 'love'] },
    { symbol: '🖤', names: ['black heart', 'love'] },
    { symbol: '🤍', names: ['white heart', 'love'] },
    { symbol: '🤎', names: ['brown heart', 'love'] },
    { symbol: '💔', names: ['broken heart', 'heartbreak', 'sad'] },
    { symbol: '❤️‍🔥', names: ['heart on fire', 'burning love'] },
    { symbol: '❤️‍🩹', names: ['mending heart', 'healing'] },
    { symbol: '💕', names: ['two hearts', 'love'] },
    { symbol: '💞', names: ['revolving hearts', 'love'] },
    { symbol: '💓', names: ['beating heart', 'love'] },
    { symbol: '💗', names: ['growing heart', 'love'] },
    { symbol: '💖', names: ['sparkling heart', 'love'] },
    { symbol: '💘', names: ['heart arrow', 'cupid', 'love'] },
    { symbol: '💝', names: ['heart box', 'gift', 'love'] },
    { symbol: '💟', names: ['heart decoration', 'love'] },
    { symbol: '☮️', names: ['peace', 'symbol'] },
    { symbol: '✝️', names: ['cross', 'christian'] },
    { symbol: '☪️', names: ['star crescent', 'islam'] },
    { symbol: '🕉️', names: ['om', 'hinduism'] },
    { symbol: '☸️', names: ['wheel dharma', 'buddhism'] },
    { symbol: '✡️', names: ['star david', 'judaism'] },
    { symbol: '🔯', names: ['dotted six pointed star'] },
    { symbol: '🕎', names: ['menorah', 'jewish'] },
    { symbol: '☯️', names: ['yin yang', 'balance'] },
    { symbol: '☦️', names: ['orthodox cross'] },
    { symbol: '🛐', names: ['place worship', 'religion'] },
    { symbol: '⛎', names: ['ophiuchus', 'zodiac'] },
    { symbol: '♈', names: ['aries', 'zodiac'] },
    { symbol: '♉', names: ['taurus', 'zodiac'] },
    { symbol: '♊', names: ['gemini', 'zodiac'] },
    { symbol: '♋', names: ['cancer', 'zodiac'] },
    { symbol: '♌', names: ['leo', 'zodiac'] },
    { symbol: '♍', names: ['virgo', 'zodiac'] },
    { symbol: '♎', names: ['libra', 'zodiac'] },
    { symbol: '♏', names: ['scorpio', 'zodiac'] },
    { symbol: '♐', names: ['sagittarius', 'zodiac'] },
    { symbol: '♑', names: ['capricorn', 'zodiac'] },
    { symbol: '♒', names: ['aquarius', 'zodiac'] },
    { symbol: '♓', names: ['pisces', 'zodiac'] },
    { symbol: '🆔', names: ['id', 'identification'] },
    { symbol: '⚛️', names: ['atom', 'science'] },
    { symbol: '🉑', names: ['accept', 'japanese'] },
    { symbol: '☢️', names: ['radioactive', 'danger'] },
    { symbol: '☣️', names: ['biohazard', 'danger'] },
    { symbol: '📴', names: ['mobile phone off'] },
    { symbol: '📳', names: ['vibration mode', 'phone'] },
    { symbol: '🈶', names: ['not free charge', 'japanese'] },
    { symbol: '🈚', names: ['free charge', 'japanese'] },
    { symbol: '🈸', names: ['application', 'japanese'] },
    { symbol: '🈺', names: ['open business', 'japanese'] },
    { symbol: '🈷️', names: ['monthly amount', 'japanese'] },
    { symbol: '✴️', names: ['eight pointed star'] },
    { symbol: '🆚', names: ['vs', 'versus'] },
    { symbol: '💮', names: ['white flower', 'japanese'] },
    { symbol: '🉐', names: ['bargain', 'japanese'] },
    { symbol: '㊙️', names: ['secret', 'japanese'] },
    { symbol: '㊗️', names: ['congratulations', 'japanese'] },
    { symbol: '🈴', names: ['passing grade', 'japanese'] },
    { symbol: '🈵', names: ['no vacancy', 'japanese'] },
    { symbol: '🈹', names: ['discount', 'japanese'] },
    { symbol: '🈲', names: ['prohibited', 'japanese'] },
    { symbol: '🅰️', names: ['a button', 'blood type'] },
    { symbol: '🅱️', names: ['b button', 'blood type'] },
    { symbol: '🆎', names: ['ab button', 'blood type'] },
    { symbol: '🆑', names: ['cl button', 'clear'] },
    { symbol: '🅾️', names: ['o button', 'blood type'] },
    { symbol: '🆘', names: ['sos', 'help', 'emergency'] },
    { symbol: '❌', names: ['x', 'cross', 'no', 'wrong'] },
    { symbol: '⭕', names: ['o', 'circle', 'yes', 'correct'] },
    { symbol: '🛑', names: ['stop', 'sign'] },
    { symbol: '⛔', names: ['no entry', 'forbidden'] },
    { symbol: '📛', names: ['name badge'] },
    { symbol: '🚫', names: ['prohibited', 'no', 'banned'] },
    { symbol: '💯', names: ['hundred', '100', 'perfect', 'score'] },
    { symbol: '💢', names: ['anger', 'angry'] },
    { symbol: '♨️', names: ['hot springs', 'steam'] },
    { symbol: '🚷', names: ['no pedestrians'] },
    { symbol: '🚯', names: ['no littering'] },
    { symbol: '🚳', names: ['no bicycles'] },
    { symbol: '🚱', names: ['non potable water'] },
    { symbol: '🔞', names: ['no one under eighteen', 'adult', '18+'] },
    { symbol: '📵', names: ['no mobile phones'] },
    { symbol: '🚭', names: ['no smoking'] },
    { symbol: '❗', names: ['exclamation', 'important', 'red'] },
    { symbol: '❕', names: ['exclamation', 'white'] },
    { symbol: '❓', names: ['question', 'red'] },
    { symbol: '❔', names: ['question', 'white'] },
    { symbol: '‼️', names: ['double exclamation', 'important'] },
    { symbol: '⁉️', names: ['exclamation question'] },
    { symbol: '🔅', names: ['dim button', 'brightness low'] },
    { symbol: '🔆', names: ['bright button', 'brightness high'] },
    { symbol: '〽️', names: ['part alternation mark'] },
    { symbol: '⚠️', names: ['warning', 'caution'] },
    { symbol: '🚸', names: ['children crossing', 'school'] },
    { symbol: '🔱', names: ['trident', 'emblem'] },
    { symbol: '⚜️', names: ['fleur de lis'] },
    { symbol: '🔰', names: ['beginner', 'japanese'] },
    { symbol: '♻️', names: ['recycle', 'recycling'] },
    { symbol: '✅', names: ['check mark', 'correct', 'done', 'complete'] },
    { symbol: '🈯', names: ['reserved', 'japanese'] },
    { symbol: '💹', names: ['chart increasing yen', 'trending'] },
    { symbol: '❇️', names: ['sparkle'] },
    { symbol: '✳️', names: ['eight spoked asterisk'] },
    { symbol: '❎', names: ['cross mark', 'x', 'no'] },
    { symbol: '🌐', names: ['globe meridians', 'world', 'internet'] },
    { symbol: '💠', names: ['diamond blue', 'cute'] },
    { symbol: 'Ⓜ️', names: ['m button', 'metro'] },
    { symbol: '🌀', names: ['cyclone', 'spiral'] },
    { symbol: '💤', names: ['zzz', 'sleep', 'sleeping'] },
    { symbol: '🏧', names: ['atm', 'cash'] },
    { symbol: '🚾', names: ['water closet', 'wc', 'bathroom'] },
    { symbol: '♿', names: ['wheelchair', 'accessible'] },
    { symbol: '🅿️', names: ['parking', 'p'] },
    { symbol: '🈳', names: ['vacancy', 'japanese'] },
    { symbol: '🈂️', names: ['service charge', 'japanese'] },
    { symbol: '🛂', names: ['passport control'] },
    { symbol: '🛃', names: ['customs'] },
    { symbol: '🛄', names: ['baggage claim'] },
    { symbol: '🛅', names: ['left luggage'] },
    { symbol: '🚹', names: ['men', 'restroom', 'bathroom'] },
    { symbol: '🚺', names: ['women', 'restroom', 'bathroom'] },
    { symbol: '🚼', names: ['baby symbol', 'nursery'] },
    { symbol: '🚻', names: ['restroom', 'bathroom'] },
    { symbol: '🚮', names: ['litter bin', 'trash'] },
    { symbol: '🎦', names: ['cinema', 'movie'] },
    { symbol: '📶', names: ['signal', 'bars', 'antenna'] },
    { symbol: '🈁', names: ['here', 'japanese'] },
    { symbol: '🔣', names: ['symbols', 'input'] },
    { symbol: 'ℹ️', names: ['information', 'info'] },
    { symbol: '🔤', names: ['abc', 'alphabet'] },
    { symbol: '🔡', names: ['abcd', 'letters'] },
    { symbol: '🔠', names: ['capital abcd', 'uppercase'] },
    { symbol: '🆖', names: ['ng', 'no good'] },
    { symbol: '🆗', names: ['ok', 'okay'] },
    { symbol: '🆙', names: ['up', 'button'] },
    { symbol: '🆒', names: ['cool', 'button'] },
    { symbol: '🆕', names: ['new', 'button'] },
    { symbol: '🆓', names: ['free', 'button'] },
    { symbol: '0️⃣', names: ['zero', '0', 'keycap'] },
    { symbol: '1️⃣', names: ['one', '1', 'keycap'] },
    { symbol: '2️⃣', names: ['two', '2', 'keycap'] },
    { symbol: '3️⃣', names: ['three', '3', 'keycap'] },
    { symbol: '4️⃣', names: ['four', '4', 'keycap'] },
    { symbol: '5️⃣', names: ['five', '5', 'keycap'] },
    { symbol: '6️⃣', names: ['six', '6', 'keycap'] },
    { symbol: '7️⃣', names: ['seven', '7', 'keycap'] },
    { symbol: '8️⃣', names: ['eight', '8', 'keycap'] },
    { symbol: '9️⃣', names: ['nine', '9', 'keycap'] },
    { symbol: '🔟', names: ['ten', '10', 'keycap'] },
    { symbol: '🔢', names: ['numbers', '1234'] },
    { symbol: '#️⃣', names: ['hash', 'hashtag', 'pound', 'keycap'] },
    { symbol: '*️⃣', names: ['asterisk', 'star', 'keycap'] },
    { symbol: '⏏️', names: ['eject', 'button'] },
    { symbol: '▶️', names: ['play', 'button', 'triangle'] },
    { symbol: '⏸️', names: ['pause', 'button'] },
    { symbol: '⏯️', names: ['play pause', 'button'] },
    { symbol: '⏹️', names: ['stop', 'button'] },
    { symbol: '⏺️', names: ['record', 'button'] },
    { symbol: '⏭️', names: ['next', 'skip', 'button'] },
    { symbol: '⏮️', names: ['previous', 'back', 'button'] },
    { symbol: '⏩', names: ['fast forward', 'button'] },
    { symbol: '⏪', names: ['rewind', 'button'] },
    { symbol: '⏫', names: ['fast up', 'button'] },
    { symbol: '⏬', names: ['fast down', 'button'] },
    { symbol: '◀️', names: ['reverse', 'left', 'button'] },
    { symbol: '🔼', names: ['up button', 'triangle'] },
    { symbol: '🔽', names: ['down button', 'triangle'] },
    { symbol: '➡️', names: ['right', 'arrow'] },
    { symbol: '⬅️', names: ['left', 'arrow'] },
    { symbol: '⬆️', names: ['up', 'arrow'] },
    { symbol: '⬇️', names: ['down', 'arrow'] },
    { symbol: '↗️', names: ['up right', 'arrow', 'northeast'] },
    { symbol: '↘️', names: ['down right', 'arrow', 'southeast'] },
    { symbol: '↙️', names: ['down left', 'arrow', 'southwest'] },
    { symbol: '↖️', names: ['up left', 'arrow', 'northwest'] },
    { symbol: '↕️', names: ['up down', 'arrow'] },
    { symbol: '↔️', names: ['left right', 'arrow'] },
    { symbol: '↪️', names: ['left arrow curving right'] },
    { symbol: '↩️', names: ['right arrow curving left'] },
    { symbol: '⤴️', names: ['right arrow curving up'] },
    { symbol: '⤵️', names: ['right arrow curving down'] },
    { symbol: '🔀', names: ['shuffle', 'random'] },
    { symbol: '🔁', names: ['repeat', 'loop'] },
    { symbol: '🔂', names: ['repeat one', 'loop'] },
    { symbol: '🔄', names: ['refresh', 'reload', 'arrows'] },
    { symbol: '🔃', names: ['reload', 'clockwise'] },
    { symbol: '🎵', names: ['music note', 'musical'] },
    { symbol: '🎶', names: ['music notes', 'musical'] },
    { symbol: '➕', names: ['plus', 'add'] },
    { symbol: '➖', names: ['minus', 'subtract'] },
    { symbol: '➗', names: ['divide', 'division'] },
    { symbol: '✖️', names: ['multiply', 'times', 'x'] },
    { symbol: '♾️', names: ['infinity'] },
    { symbol: '💲', names: ['dollar', 'money', 'currency'] },
    { symbol: '💱', names: ['currency exchange', 'forex'] },
    { symbol: '™️', names: ['trademark', 'tm'] },
    { symbol: '©️', names: ['copyright'] },
    { symbol: '®️', names: ['registered'] },
    { symbol: '〰️', names: ['wavy dash'] },
    { symbol: '➰', names: ['curly loop'] },
    { symbol: '➿', names: ['double curly loop'] },
    { symbol: '🔚', names: ['end', 'arrow'] },
    { symbol: '🔙', names: ['back', 'arrow'] },
    { symbol: '🔛', names: ['on', 'arrow'] },
    { symbol: '🔝', names: ['top', 'arrow', 'up'] },
    { symbol: '🔜', names: ['soon', 'arrow'] },

    // Weather & Nature
    { symbol: '☀️', names: ['sun', 'sunny', 'bright'] },
    { symbol: '🌤️', names: ['sun behind cloud', 'partly cloudy'] },
    { symbol: '⛅', names: ['sun behind cloud', 'partly cloudy'] },
    { symbol: '🌥️', names: ['sun behind large cloud'] },
    { symbol: '☁️', names: ['cloud', 'cloudy'] },
    { symbol: '🌦️', names: ['sun behind rain cloud'] },
    { symbol: '🌧️', names: ['rain', 'rainy'] },
    { symbol: '⛈️', names: ['storm', 'thunder', 'lightning'] },
    { symbol: '🌩️', names: ['cloud lightning'] },
    { symbol: '🌨️', names: ['snow', 'snowing'] },
    { symbol: '❄️', names: ['snowflake', 'snow', 'cold'] },
    { symbol: '☃️', names: ['snowman', 'snow'] },
    { symbol: '⛄', names: ['snowman without snow'] },
    { symbol: '💨', names: ['wind', 'dash', 'fast'] },
    { symbol: '💧', names: ['drop', 'water', 'droplet'] },
    { symbol: '💦', names: ['sweat drops', 'water'] },
    { symbol: '☔', names: ['umbrella', 'rain'] },
    { symbol: '☂️', names: ['umbrella'] },
    { symbol: '🌊', names: ['wave', 'ocean', 'water'] },
    { symbol: '🌫️', names: ['fog', 'foggy'] },
    { symbol: '🌪️', names: ['tornado', 'cyclone'] },
    { symbol: '🌬️', names: ['wind face', 'blowing'] },
    { symbol: '🌀', names: ['cyclone', 'hurricane'] },
    { symbol: '🌈', names: ['rainbow', 'pride'] },
    { symbol: '🌂', names: ['closed umbrella'] },
    { symbol: '☄️', names: ['comet', 'meteor'] },
    { symbol: '⭐', names: ['star', 'white'] },
    { symbol: '🌟', names: ['glowing star', 'shining'] },
    { symbol: '✨', names: ['sparkles', 'shiny', 'glitter'] },
    { symbol: '⚡', names: ['lightning', 'bolt', 'electricity', 'zap'] },
    { symbol: '🔥', names: ['fire', 'flame', 'hot', 'lit'] },
    { symbol: '💥', names: ['boom', 'explosion', 'collision'] },
    { symbol: '☀️', names: ['sun'] },
    { symbol: '🌝', names: ['full moon face', 'moon'] },
    { symbol: '🌛', names: ['first quarter moon face'] },
    { symbol: '🌜', names: ['last quarter moon face'] },
    { symbol: '🌚', names: ['new moon face'] },
    { symbol: '🌕', names: ['full moon'] },
    { symbol: '🌖', names: ['waning gibbous moon'] },
    { symbol: '🌗', names: ['last quarter moon'] },
    { symbol: '🌘', names: ['waning crescent moon'] },
    { symbol: '🌑', names: ['new moon'] },
    { symbol: '🌒', names: ['waxing crescent moon'] },
    { symbol: '🌓', names: ['first quarter moon'] },
    { symbol: '🌔', names: ['waxing gibbous moon'] },
    { symbol: '🌙', names: ['crescent moon'] },
    { symbol: '🌎', names: ['earth americas', 'globe', 'world'] },
    { symbol: '🌍', names: ['earth africa', 'globe', 'world'] },
    { symbol: '🌏', names: ['earth asia', 'globe', 'world'] },
    { symbol: '🪐', names: ['saturn', 'planet', 'ringed'] },
    { symbol: '💫', names: ['dizzy', 'stars'] },
    { symbol: '⭐', names: ['star'] },
    { symbol: '🌠', names: ['shooting star', 'falling star'] },
    { symbol: '🌌', names: ['milky way', 'galaxy', 'space'] },

    // Flags - Just a few popular ones
    { symbol: '🏁', names: ['checkered flag', 'racing', 'finish'] },
    { symbol: '🚩', names: ['red flag', 'flag'] },
    { symbol: '🎌', names: ['crossed flags', 'japanese'] },
    { symbol: '🏴', names: ['black flag', 'pirate'] },
    { symbol: '🏳️', names: ['white flag', 'surrender'] },
    { symbol: '🏳️‍🌈', names: ['rainbow flag', 'pride', 'lgbtq'] },
    { symbol: '🏴‍☠️', names: ['pirate flag', 'jolly roger'] },
];
