// Comprehensive symbol database with searchable names
const symbols = [
    // Greek Letters - Lowercase
    { symbol: 'α', names: ['alpha', 'greek'] },
    { symbol: 'β', names: ['beta', 'greek'] },
    { symbol: 'γ', names: ['gamma', 'greek'] },
    { symbol: 'δ', names: ['delta', 'greek'] },
    { symbol: 'ε', names: ['epsilon', 'greek'] },
    { symbol: 'ζ', names: ['zeta', 'greek'] },
    { symbol: 'η', names: ['eta', 'greek'] },
    { symbol: 'θ', names: ['theta', 'greek'] },
    { symbol: 'ι', names: ['iota', 'greek'] },
    { symbol: 'κ', names: ['kappa', 'greek'] },
    { symbol: 'λ', names: ['lambda', 'greek'] },
    { symbol: 'μ', names: ['mu', 'micro', 'greek'] },
    { symbol: 'ν', names: ['nu', 'greek'] },
    { symbol: 'ξ', names: ['xi', 'greek'] },
    { symbol: 'ο', names: ['omicron', 'greek'] },
    { symbol: 'π', names: ['pi', 'greek'] },
    { symbol: 'ρ', names: ['rho', 'greek'] },
    { symbol: 'ς', names: ['sigma final', 'greek'] },
    { symbol: 'σ', names: ['sigma', 'greek'] },
    { symbol: 'τ', names: ['tau', 'greek'] },
    { symbol: 'υ', names: ['upsilon', 'greek'] },
    { symbol: 'φ', names: ['phi', 'greek'] },
    { symbol: 'χ', names: ['chi', 'greek'] },
    { symbol: 'ψ', names: ['psi', 'greek'] },
    { symbol: 'ω', names: ['omega', 'greek'] },

    // Greek Letters - Uppercase
    { symbol: 'Α', names: ['Alpha', 'greek uppercase'] },
    { symbol: 'Β', names: ['Beta', 'greek uppercase'] },
    { symbol: 'Γ', names: ['Gamma', 'greek uppercase'] },
    { symbol: 'Δ', names: ['Delta', 'greek uppercase', 'triangle'] },
    { symbol: 'Ε', names: ['Epsilon', 'greek uppercase'] },
    { symbol: 'Ζ', names: ['Zeta', 'greek uppercase'] },
    { symbol: 'Η', names: ['Eta', 'greek uppercase'] },
    { symbol: 'Θ', names: ['Theta', 'greek uppercase'] },
    { symbol: 'Ι', names: ['Iota', 'greek uppercase'] },
    { symbol: 'Κ', names: ['Kappa', 'greek uppercase'] },
    { symbol: 'Λ', names: ['Lambda', 'greek uppercase'] },
    { symbol: 'Μ', names: ['Mu', 'greek uppercase'] },
    { symbol: 'Ν', names: ['Nu', 'greek uppercase'] },
    { symbol: 'Ξ', names: ['Xi', 'greek uppercase'] },
    { symbol: 'Ο', names: ['Omicron', 'greek uppercase'] },
    { symbol: 'Π', names: ['Pi', 'greek uppercase', 'product'] },
    { symbol: 'Ρ', names: ['Rho', 'greek uppercase'] },
    { symbol: 'Σ', names: ['Sigma', 'greek uppercase', 'sum'] },
    { symbol: 'Τ', names: ['Tau', 'greek uppercase'] },
    { symbol: 'Υ', names: ['Upsilon', 'greek uppercase'] },
    { symbol: 'Φ', names: ['Phi', 'greek uppercase'] },
    { symbol: 'Χ', names: ['Chi', 'greek uppercase'] },
    { symbol: 'Ψ', names: ['Psi', 'greek uppercase'] },
    { symbol: 'Ω', names: ['Omega', 'greek uppercase', 'ohm'] },

    // Math Operators
    { symbol: '+', names: ['plus', 'add', 'addition'] },
    { symbol: '−', names: ['minus', 'subtract', 'subtraction'] },
    { symbol: '×', names: ['times', 'multiply', 'multiplication', 'cross'] },
    { symbol: '÷', names: ['divide', 'division'] },
    { symbol: '±', names: ['plus minus', 'plus or minus'] },
    { symbol: '∓', names: ['minus plus', 'minus or plus'] },
    { symbol: '=', names: ['equals', 'equal'] },
    { symbol: '≠', names: ['not equal', 'not equals'] },
    { symbol: '≈', names: ['approximately', 'almost equal'] },
    { symbol: '≡', names: ['equivalent', 'identical', 'congruent'] },
    { symbol: '≢', names: ['not equivalent', 'not identical'] },
    { symbol: '∼', names: ['similar', 'tilde'] },
    { symbol: '≅', names: ['approximately equal', 'congruent'] },
    { symbol: '∝', names: ['proportional', 'proportional to'] },

    // Comparison
    { symbol: '<', names: ['less than', 'less'] },
    { symbol: '>', names: ['greater than', 'greater'] },
    { symbol: '≤', names: ['less than or equal', 'less equal'] },
    { symbol: '≥', names: ['greater than or equal', 'greater equal'] },
    { symbol: '≪', names: ['much less than', 'much less'] },
    { symbol: '≫', names: ['much greater than', 'much greater'] },

    // Arrows
    { symbol: '←', names: ['left arrow', 'arrow left', 'leftarrow'] },
    { symbol: '→', names: ['right arrow', 'arrow right', 'rightarrow', 'implies'] },
    { symbol: '↑', names: ['up arrow', 'arrow up', 'uparrow'] },
    { symbol: '↓', names: ['down arrow', 'arrow down', 'downarrow'] },
    { symbol: '↔', names: ['left right arrow', 'arrow left right', 'bidirectional'] },
    { symbol: '↕', names: ['up down arrow', 'arrow up down', 'vertical'] },
    { symbol: '⇐', names: ['left double arrow', 'double arrow left'] },
    { symbol: '⇒', names: ['right double arrow', 'double arrow right', 'implies'] },
    { symbol: '⇑', names: ['up double arrow', 'double arrow up'] },
    { symbol: '⇓', names: ['down double arrow', 'double arrow down'] },
    { symbol: '⇔', names: ['left right double arrow', 'iff', 'if and only if'] },
    { symbol: '⇕', names: ['up down double arrow'] },
    { symbol: '↖', names: ['northwest arrow', 'arrow northwest'] },
    { symbol: '↗', names: ['northeast arrow', 'arrow northeast'] },
    { symbol: '↘', names: ['southeast arrow', 'arrow southeast'] },
    { symbol: '↙', names: ['southwest arrow', 'arrow southwest'] },
    { symbol: '↺', names: ['counterclockwise arrow', 'rotate left'] },
    { symbol: '↻', names: ['clockwise arrow', 'rotate right'] },

    // Set Theory
    { symbol: '∈', names: ['element of', 'in', 'member'] },
    { symbol: '∉', names: ['not element of', 'not in', 'not member'] },
    { symbol: '∋', names: ['contains', 'contains as member'] },
    { symbol: '∌', names: ['not contains', 'does not contain'] },
    { symbol: '⊂', names: ['subset', 'subset of'] },
    { symbol: '⊃', names: ['superset', 'superset of'] },
    { symbol: '⊆', names: ['subset or equal', 'subset equal'] },
    { symbol: '⊇', names: ['superset or equal', 'superset equal'] },
    { symbol: '⊄', names: ['not subset'] },
    { symbol: '⊅', names: ['not superset'] },
    { symbol: '∪', names: ['union', 'cup'] },
    { symbol: '∩', names: ['intersection', 'cap'] },
    { symbol: '∅', names: ['empty set', 'null set', 'emptyset'] },
    { symbol: '∖', names: ['set difference', 'set minus'] },
    { symbol: '℘', names: ['power set', 'weierstrass'] },

    // Logic
    { symbol: '∧', names: ['and', 'logical and', 'wedge'] },
    { symbol: '∨', names: ['or', 'logical or', 'vee'] },
    { symbol: '¬', names: ['not', 'negation', 'logical not'] },
    { symbol: '⊕', names: ['xor', 'exclusive or', 'oplus'] },
    { symbol: '∀', names: ['for all', 'universal quantifier'] },
    { symbol: '∃', names: ['exists', 'there exists', 'existential quantifier'] },
    { symbol: '∄', names: ['not exists', 'there does not exist'] },
    { symbol: '⊤', names: ['true', 'top', 'tautology'] },
    { symbol: '⊥', names: ['false', 'bottom', 'contradiction', 'perpendicular'] },
    { symbol: '⊢', names: ['proves', 'entails', 'turnstile'] },
    { symbol: '⊨', names: ['models', 'semantic entailment'] },

    // Calculus & Analysis
    { symbol: '∫', names: ['integral', 'integrate'] },
    { symbol: '∬', names: ['double integral'] },
    { symbol: '∭', names: ['triple integral'] },
    { symbol: '∮', names: ['contour integral', 'line integral'] },
    { symbol: '∂', names: ['partial', 'partial derivative'] },
    { symbol: '∇', names: ['nabla', 'gradient', 'del'] },
    { symbol: '∆', names: ['delta', 'laplacian', 'change'] },
    { symbol: '∞', names: ['infinity', 'infinite'] },
    { symbol: '∑', names: ['sum', 'summation', 'sigma'] },
    { symbol: '∏', names: ['product', 'pi'] },
    { symbol: '∐', names: ['coproduct'] },
    { symbol: 'ℓ', names: ['ell', 'script l'] },
    { symbol: 'ℜ', names: ['real part', 'fraktur R'] },
    { symbol: 'ℑ', names: ['imaginary part', 'fraktur I'] },

    // Special Numbers
    { symbol: 'ℕ', names: ['natural numbers', 'naturals'] },
    { symbol: 'ℤ', names: ['integers'] },
    { symbol: 'ℚ', names: ['rational numbers', 'rationals'] },
    { symbol: 'ℝ', names: ['real numbers', 'reals'] },
    { symbol: 'ℂ', names: ['complex numbers', 'complex'] },
    { symbol: 'ℙ', names: ['prime numbers', 'primes'] },
    { symbol: 'ℍ', names: ['quaternions'] },
    { symbol: '𝒩', names: ['script N', 'normal distribution', 'script capital N'] },

    // Geometry
    { symbol: '°', names: ['degree', 'degrees'] },
    { symbol: '∠', names: ['angle'] },
    { symbol: '∟', names: ['right angle'] },
    { symbol: '⊥', names: ['perpendicular', 'orthogonal'] },
    { symbol: '∥', names: ['parallel'] },
    { symbol: '∦', names: ['not parallel'] },
    { symbol: '△', names: ['triangle'] },
    { symbol: '□', names: ['square', 'box'] },
    { symbol: '○', names: ['circle'] },
    { symbol: '◊', names: ['diamond', 'lozenge'] },

    // Miscellaneous Math
    { symbol: '√', names: ['square root', 'root', 'radical'] },
    { symbol: '∛', names: ['cube root', 'third root'] },
    { symbol: '∜', names: ['fourth root'] },
    { symbol: '!', names: ['factorial', 'exclamation'] },
    { symbol: '‰', names: ['per mille', 'per thousand'] },
    { symbol: '%', names: ['percent', 'percentage'] },
    { symbol: '~', names: ['tilde', 'approximately', 'similar'] },
    { symbol: '∴', names: ['therefore'] },
    { symbol: '∵', names: ['because', 'since'] },
    { symbol: '⋯', names: ['ellipsis', 'dots', 'horizontal dots'] },
    { symbol: '⋮', names: ['vertical ellipsis', 'vertical dots'] },
    { symbol: '⋱', names: ['diagonal ellipsis', 'diagonal dots'] },
    { symbol: '†', names: ['dagger'] },
    { symbol: '‡', names: ['double dagger'] },
    { symbol: '℧', names: ['mho', 'inverted ohm'] },
    { symbol: 'ℏ', names: ['h bar', 'hbar', 'planck'] },
    { symbol: 'Å', names: ['angstrom'] },
    { symbol: '∅', names: ['diameter', 'empty', 'null'] },

    // Fractions
    { symbol: '½', names: ['half', 'one half'] },
    { symbol: '⅓', names: ['one third'] },
    { symbol: '⅔', names: ['two thirds'] },
    { symbol: '¼', names: ['quarter', 'one quarter'] },
    { symbol: '¾', names: ['three quarters'] },
    { symbol: '⅕', names: ['one fifth'] },
    { symbol: '⅖', names: ['two fifths'] },
    { symbol: '⅗', names: ['three fifths'] },
    { symbol: '⅘', names: ['four fifths'] },
    { symbol: '⅙', names: ['one sixth'] },
    { symbol: '⅚', names: ['five sixths'] },
    { symbol: '⅛', names: ['one eighth'] },
    { symbol: '⅜', names: ['three eighths'] },
    { symbol: '⅝', names: ['five eighths'] },
    { symbol: '⅞', names: ['seven eighths'] },

    // Superscripts
    { symbol: '⁰', names: ['superscript 0', 'power 0'] },
    { symbol: '¹', names: ['superscript 1', 'power 1'] },
    { symbol: '²', names: ['superscript 2', 'squared', 'power 2'] },
    { symbol: '³', names: ['superscript 3', 'cubed', 'power 3'] },
    { symbol: '⁴', names: ['superscript 4', 'power 4'] },
    { symbol: '⁵', names: ['superscript 5', 'power 5'] },
    { symbol: '⁶', names: ['superscript 6', 'power 6'] },
    { symbol: '⁷', names: ['superscript 7', 'power 7'] },
    { symbol: '⁸', names: ['superscript 8', 'power 8'] },
    { symbol: '⁹', names: ['superscript 9', 'power 9'] },
    { symbol: '⁺', names: ['superscript plus'] },
    { symbol: '⁻', names: ['superscript minus'] },
    { symbol: '⁼', names: ['superscript equals'] },
    { symbol: '⁽', names: ['superscript left parenthesis'] },
    { symbol: '⁾', names: ['superscript right parenthesis'] },
    { symbol: 'ⁱ', names: ['superscript i', 'power i'] },
    { symbol: 'ⁿ', names: ['superscript n', 'power n'] },
    { symbol: 'ᵃ', names: ['superscript a'] },
    { symbol: 'ᵇ', names: ['superscript b'] },
    { symbol: 'ᶜ', names: ['superscript c'] },
    { symbol: 'ᵈ', names: ['superscript d'] },
    { symbol: 'ᵉ', names: ['superscript e'] },
    { symbol: 'ᶠ', names: ['superscript f'] },
    { symbol: 'ᵍ', names: ['superscript g'] },
    { symbol: 'ʰ', names: ['superscript h'] },
    { symbol: 'ʲ', names: ['superscript j'] },
    { symbol: 'ᵏ', names: ['superscript k'] },
    { symbol: 'ˡ', names: ['superscript l'] },
    { symbol: 'ᵐ', names: ['superscript m'] },
    { symbol: 'ᵒ', names: ['superscript o'] },
    { symbol: 'ᵖ', names: ['superscript p'] },
    { symbol: 'ʳ', names: ['superscript r'] },
    { symbol: 'ˢ', names: ['superscript s'] },
    { symbol: 'ᵗ', names: ['superscript t'] },
    { symbol: 'ᵘ', names: ['superscript u'] },
    { symbol: 'ᵛ', names: ['superscript v'] },
    { symbol: 'ʷ', names: ['superscript w'] },
    { symbol: 'ˣ', names: ['superscript x'] },
    { symbol: 'ʸ', names: ['superscript y'] },
    { symbol: 'ᶻ', names: ['superscript z'] },
    { symbol: 'ᴬ', names: ['superscript A'] },
    { symbol: 'ᴮ', names: ['superscript B'] },
    { symbol: 'ᴰ', names: ['superscript D'] },
    { symbol: 'ᴱ', names: ['superscript E'] },
    { symbol: 'ᴳ', names: ['superscript G'] },
    { symbol: 'ᴴ', names: ['superscript H'] },
    { symbol: 'ᴵ', names: ['superscript I'] },
    { symbol: 'ᴶ', names: ['superscript J'] },
    { symbol: 'ᴷ', names: ['superscript K'] },
    { symbol: 'ᴸ', names: ['superscript L'] },
    { symbol: 'ᴹ', names: ['superscript M'] },
    { symbol: 'ᴺ', names: ['superscript N'] },
    { symbol: 'ᴼ', names: ['superscript O'] },
    { symbol: 'ᴾ', names: ['superscript P'] },
    { symbol: 'ᴿ', names: ['superscript R'] },
    { symbol: 'ᵀ', names: ['superscript T'] },
    { symbol: 'ᵁ', names: ['superscript U'] },
    { symbol: 'ⱽ', names: ['superscript V'] },
    { symbol: 'ᵂ', names: ['superscript W'] },

    // Subscripts
    { symbol: '₀', names: ['subscript 0'] },
    { symbol: '₁', names: ['subscript 1'] },
    { symbol: '₂', names: ['subscript 2'] },
    { symbol: '₃', names: ['subscript 3'] },
    { symbol: '₄', names: ['subscript 4'] },
    { symbol: '₅', names: ['subscript 5'] },
    { symbol: '₆', names: ['subscript 6'] },
    { symbol: '₇', names: ['subscript 7'] },
    { symbol: '₈', names: ['subscript 8'] },
    { symbol: '₉', names: ['subscript 9'] },
    { symbol: '₊', names: ['subscript plus'] },
    { symbol: '₋', names: ['subscript minus'] },
    { symbol: '₌', names: ['subscript equals'] },
    { symbol: '₍', names: ['subscript left parenthesis'] },
    { symbol: '₎', names: ['subscript right parenthesis'] },
    { symbol: 'ₐ', names: ['subscript a'] },
    { symbol: 'ₑ', names: ['subscript e'] },
    { symbol: 'ₕ', names: ['subscript h'] },
    { symbol: 'ᵢ', names: ['subscript i'] },
    { symbol: 'ⱼ', names: ['subscript j'] },
    { symbol: 'ₖ', names: ['subscript k'] },
    { symbol: 'ₗ', names: ['subscript l'] },
    { symbol: 'ₘ', names: ['subscript m'] },
    { symbol: 'ₙ', names: ['subscript n'] },
    { symbol: 'ₒ', names: ['subscript o'] },
    { symbol: 'ₚ', names: ['subscript p'] },
    { symbol: 'ᵣ', names: ['subscript r'] },
    { symbol: 'ₛ', names: ['subscript s'] },
    { symbol: 'ₜ', names: ['subscript t'] },
    { symbol: 'ᵤ', names: ['subscript u'] },
    { symbol: 'ᵥ', names: ['subscript v'] },
    { symbol: 'ₓ', names: ['subscript x'] },

    // Currency
    { symbol: '€', names: ['euro'] },
    { symbol: '$', names: ['dollar'] },
    { symbol: '£', names: ['pound', 'sterling'] },
    { symbol: '¥', names: ['yen', 'yuan'] },
    { symbol: '¢', names: ['cent'] },
    { symbol: '₹', names: ['rupee'] },
    { symbol: '₽', names: ['ruble'] },
    { symbol: '₿', names: ['bitcoin'] },

    // Other Useful Symbols
    { symbol: '✓', names: ['check', 'checkmark', 'tick'] },
    { symbol: '✗', names: ['x mark', 'cross', 'ballot x'] },
    { symbol: '★', names: ['star', 'filled star'] },
    { symbol: '☆', names: ['star outline', 'empty star'] },
    { symbol: '•', names: ['bullet', 'dot'] },
    { symbol: '◦', names: ['circle bullet', 'white bullet'] },
    { symbol: '§', names: ['section', 'section sign'] },
    { symbol: '¶', names: ['paragraph', 'pilcrow'] },
    { symbol: '©', names: ['copyright'] },
    { symbol: '®', names: ['registered', 'registered trademark'] },
    { symbol: '™', names: ['trademark'] },
    { symbol: '–', names: ['en dash', 'dash'] },
    { symbol: '—', names: ['em dash', 'long dash'] },
    { symbol: '\'', names: ['left single quote', 'single quote'] },
    { symbol: '\'', names: ['right single quote', 'single quote'] },
    { symbol: '"', names: ['left double quote', 'double quote'] },
    { symbol: '"', names: ['right double quote', 'double quote'] },

    // Three dots and ellipsis variations
    { symbol: '…', names: ['ellipsis', 'three dots', 'horizontal ellipsis', 'dot dot dot'] },
    { symbol: '⋯', names: ['midline horizontal ellipsis', 'three dots', 'centered dots'] },
    { symbol: '⋮', names: ['vertical ellipsis', 'three dots vertical', 'vertical three dots'] },
    { symbol: '⋰', names: ['up right diagonal ellipsis', 'three dots diagonal', 'ascending dots'] },
    { symbol: '⋱', names: ['down right diagonal ellipsis', 'three dots diagonal', 'descending dots'] },
    { symbol: '︙', names: ['vertical ellipsis presentation', 'three dots vertical', 'vertical menu'] },
    { symbol: '⁝', names: ['tricolon', 'three dots vertical'] },
    { symbol: '⸬', names: ['double comma', 'two dots'] },
    { symbol: '⸭', names: ['triple comma', 'three commas'] },
];
